command:
  - sh
  - -c
  - PORT=$DATABRICKS_APP_PORT npm run start

env:
  - name: NEXT_PUBLIC_SUPABASE_URL
    valueFrom: supabase-url
  - name: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
    valueFrom: supabase-publishable-key
  - name: OPENAI_API_KEY
    valueFrom: openai-api-key
