// Builds data/series.ts by matching scraped row data (rows.json) to local asset filenames.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const rows = JSON.parse(fs.readFileSync(path.join(ROOT, 'rows.json'), 'utf8'));
const assetDir = path.join(ROOT, 'public', 'assets');

const files = fs.readdirSync(assetDir).filter((f) => f.endsWith('.webp'));

// Non-series assets we must not hand out as cover art.
const EXCLUDE = new Set([
  'Billboard_Strip_Image-0.webp',
  'Billboard_Strip_Image-1.webp',
  'Billboard_Strip_Image-3.webp',
  'Download_on_the_App_Store.webp',
  'Get_it_on_Google_Play.webp',
  'Pocket_FM_App.webp',
  'Cassettes.webp',
  'image_80x100_191.webp',
]);

const covers = files.filter((f) => !EXCLUDE.has(f));

/** Reduce a string to comparable ascii word tokens. */
function tokens(s) {
  return s
    .replace(/[ऀ-ॿ]+/g, ' ') // drop Devanagari
    .replace(/\.webp$/i, '')
    .replace(/[_|:\-–—'’"“”().,!?&]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase()
    .split(' ')
    .filter((t) => t && t !== 'author');
}

const fileTokens = new Map(covers.map((f) => [f, tokens(f)]));

function score(aTok, bTok) {
  if (!aTok.length || !bTok.length) return 0;
  const b = new Set(bTok);
  let hit = 0;
  for (const t of aTok) if (b.has(t)) hit++;
  return (2 * hit) / (aTok.length + bTok.length);
}

const used = new Set();

/** Best unused local file for a scraped title. */
function matchFile(title) {
  const tt = tokens(title);
  let best = null;
  let bestScore = 0;
  for (const [f, ft] of fileTokens) {
    if (used.has(f)) continue;
    const s = score(tt, ft);
    if (s > bestScore) {
      bestScore = s;
      best = f;
    }
  }
  if (best && bestScore >= 0.5) {
    used.add(best);
    return best;
  }
  return null;
}

/** Any remaining unused file, for Devanagari-only titles that can't be matched. */
function anyUnused() {
  for (const f of covers) {
    if (!used.has(f)) {
      used.add(f);
      return f;
    }
  }
  return null;
}

// English display title: strip Devanagari and the "Author - X" suffix.
function displayTitle(raw) {
  let t = raw
    .replace(/[ऀ-ॿ]+/g, '')
    .replace(/\s*\|\s*/g, ' | ')
    .split('|')
    .map((p) => p.trim())
    .filter((p) => p && !/^author\s*-/i.test(p))
    .join(' | ');
  return t.replace(/\s+/g, ' ').trim();
}

function authorOf(raw) {
  const m = raw.match(/Author\s*-\s*([^|]+)$/i);
  return m ? m[1].trim() : null;
}

// Genre per row, so cards can show something sensible.
const ROW_GENRE = {
  'Epic Fantasy': 'Epic Fantasy',
  'Thriller & Horror': 'Thriller',
  'Wedlock Romance': 'Romance',
  'Male Drama': 'Drama',
  'Eastern Fantasy': 'Eastern Fantasy',
  'Female Drama': 'Drama',
  'Magical Realism': 'Magical Realism',
  'Contemporary Romance': 'Romance',
  'Horror Thriller': 'Horror',
  Systems: 'System',
  'Action Thriller': 'Action',
  'Contemporary Fantasy': 'Fantasy',
  'Low Fantasy': 'Fantasy',
  'Sci-Fi': 'Sci-Fi',
};

const seriesById = new Map();
const slugCount = new Map();

function slugify(s) {
  const base =
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 48) || 'series';
  const n = (slugCount.get(base) ?? 0) + 1;
  slugCount.set(base, n);
  return n === 1 ? base : `${base}-${n}`;
}

const byTitle = new Map();
const outRows = [];

for (const r of rows) {
  if (!r.items.length) continue; // Spotlight handled separately
  const ids = [];
  for (const it of r.items) {
    let id = byTitle.get(it.title);
    if (!id) {
      const image = matchFile(it.title) ?? anyUnused();
      if (!image) continue; // ran out of art
      id = slugify(displayTitle(it.title) || it.title);
      byTitle.set(it.title, id);
      seriesById.set(id, {
        id,
        title: displayTitle(it.title) || it.title,
        author: authorOf(it.title),
        image: `/assets/${image}`,
        badge: it.badge,
        plays: it.plays,
        rating: it.rating,
        genre: ROW_GENRE[r.row] ?? null,
      });
    }
    ids.push(id);
  }
  outRows.push({
    title: r.row,
    variant: r.row === 'Popular on Pocket FM' ? 'ranked' : 'default',
    ids,
  });
}

// Hero slides: the four Spotlight titles, taken from the top of Top Picks.
const HERO_TITLES = [
  'The Return of Tiger',
  'Mahagatha',
  'Bechara Billionaire',
  'Super Yoddha',
];
const heroIds = HERO_TITLES.map((want) => {
  for (const [id, s] of seriesById) {
    if (s.title.toLowerCase().startsWith(want.toLowerCase())) return id;
  }
  return null;
}).filter(Boolean);

const ts = `// GENERATED by scripts/build-seed.mjs — edit that script, not this file.
// Seed catalog for the home page. Swap this module for a Lakebase query later;
// the components only depend on the exported types.

export type Series = {
  id: string;
  title: string;
  author: string | null;
  image: string;
  /** Short badge shown over the cover art, e.g. "170M+". */
  badge: string | null;
  /** Full play count shown under the art, e.g. "170.1M". */
  plays: string | null;
  rating: string | null;
  genre: string | null;
};

export type Row = {
  title: string;
  variant: 'default' | 'ranked';
  ids: string[];
};

export const SERIES: Record<string, Series> = ${JSON.stringify(
  Object.fromEntries(seriesById),
  null,
  2,
)};

export const ROWS: Row[] = ${JSON.stringify(outRows, null, 2)};

/** Titles featured in the hero carousel, in order. */
export const HERO_IDS: string[] = ${JSON.stringify(heroIds, null, 2)};

export function getSeries(id: string): Series {
  const s = SERIES[id];
  if (!s) throw new Error(\`Unknown series: \${id}\`);
  return s;
}

export function seriesFor(ids: string[]): Series[] {
  return ids.map(getSeries);
}
`;

fs.mkdirSync(path.join(ROOT, 'data'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'data', 'series.ts'), ts);

console.log(`series: ${seriesById.size}`);
console.log(`rows: ${outRows.length}`);
console.log(`covers used: ${used.size} / ${covers.length}`);
console.log(`hero: ${heroIds.join(', ')}`);
